DROP
ALL OBJECTS;
CREATE TABLE USER_LOGIN
(
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    user_name           varchar2(100),
    email               VARCHAR(250) DEFAULT NULL,
    password            VARCHAR2(300),
    email_Verified      varchar2(10),
    account_Locked      varchar2(10),
    account_Expired     varchar2(10),
    credentials_Expired varchar2(10),
    status              varchar2(1),
    roles               varchar2(250),
    provider            varchar2(250),
    provider_Id         varchar2(250),
    IMAGE_URL           varchar2(250),
    blocked_by          varchar2(250)
);

CREATE TABLE USER_GAME
(
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    user_name           varchar2(100),
    password            VARCHAR2(300),
);

CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID INT AUTO_INCREMENT PRIMARY KEY,
    VERSION         INT,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
);

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    VERSION          INT,
    JOB_INSTANCE_ID  INT NOT NULL,
    CREATE_TIME      DATETIME(6) NOT NULL,
    START_TIME       DATETIME(6) DEFAULT NULL,
    END_TIME         DATETIME(6) DEFAULT NULL,
    STATUS           VARCHAR(10),
    EXIT_CODE        VARCHAR(2500),
    EXIT_MESSAGE     VARCHAR(2500),
    LAST_UPDATED     DATETIME(6),
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
        references BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID INT          NOT NULL,
    PARAMETER_NAME   VARCHAR(100) NOT NULL,
    PARAMETER_TYPE   VARCHAR(100) NOT NULL,
    PARAMETER_VALUE  VARCHAR(2500),
    IDENTIFYING      CHAR(1)      NOT NULL,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
        references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  INT          NOT NULL PRIMARY KEY,
    VERSION            INT          NOT NULL,
    STEP_NAME          VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID   INT          NOT NULL,
    CREATE_TIME        DATETIME(6) NOT NULL,
    START_TIME         DATETIME(6) DEFAULT NULL,
    END_TIME           DATETIME(6) DEFAULT NULL,
    STATUS             VARCHAR(10),
    COMMIT_COUNT       INT,
    READ_COUNT         INT,
    FILTER_COUNT       INT,
    WRITE_COUNT        INT,
    READ_SKIP_COUNT    INT,
    WRITE_SKIP_COUNT   INT,
    PROCESS_SKIP_COUNT INT,
    ROLLBACK_COUNT     INT,
    EXIT_CODE          VARCHAR(2500),
    EXIT_MESSAGE       VARCHAR(2500),
    LAST_UPDATED       DATETIME(6),
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
        references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  INT           NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
        references BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   INT           NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
        references BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE SEQUENCE BATCH_JOB_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 202700
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 202700
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 202700
    NOCACHE
    NOCYCLE;